apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  annotations:
  name: example-kc
  namespace: rhbk
spec:
  db:
    database: rhbk
    host: postgres-db
    passwordSecret:
      key: password
      name: keycloak-db-secret
    usernameSecret:
      key: username
      name: keycloak-db-secret
    vendor: postgres
  hostname:
    strict: false
  http:
    httpEnabled: true
  instances: 1
  proxy:
    headers: xforwarded
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 256Mi
